### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by morwen80** [learn-co-curriculum/fe-code-along-ex-1#10]
You ask to download a picture on the following link: http://jonathangrover.com/teaching/students/fe/intro-pic.jpg

But the image does not exist and we are redirected to a webpage

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
