### ISSUE TITLE
Link to intro-pic is no longer working

### ISSUE THREAD

**Issue by jrodden1** [learn-co-curriculum/fe-code-along-ex-1#11]
![link broken](https://user-images.githubusercontent.com/39208179/59170008-d7970800-8af9-11e9-8700-c18b4f948c7a.gif)

The intro-pic link does seem to link to the picture anymore.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
