### ISSUE TITLE
Link for image does not work.

### ISSUE THREAD

**Issue by dimacodes** [learn-co-curriculum/fe-code-along-ex-1#4]

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by emilycroft** [comment]
Looks like this link still doesn't work, and there appears to be a bug with the "Report A Bug" selection (some real irony!). Is there any other way to let someone know that there's a issue?

**Comment by drakeltheryuujin** [comment]
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
