### ISSUE TITLE
dead link in this exercise

### ISSUE THREAD

**Issue by krandles** [learn-co-curriculum/fe-code-along-ex-1#5]
the image linked to on this page, to be used in the exercise (http://jonathangrover.com/teaching/students/fe/intro-pic.jpg) no longer exists, link redirects to index.php

**Comment by hansenjl** [comment]
A few students have asked about this ^^

**Comment by Enoch2k2** [comment]
As a temporary fix, you can download these files from my github:

Picture: https://github.com/Enoch2k2/CSS-Styling-v-000/blob/master/images/intro-pic.jpg

Videos: 
https://github.com/Enoch2k2/CSS-Styling-v-000/blob/master/videos/real-estate.mp4
https://github.com/Enoch2k2/CSS-Styling-v-000/blob/master/videos/real-estate.ogv

Just click on download

**Comment by kwebster2** [comment]
@maxwellbenton 
This is still an issue

**Comment by drakeltheryuujin** [comment]
We have updated the materials and believe your issue to have been resolved.
