### ISSUE TITLE
OUTDATED: Git commands in instructions are no longer valid

### ISSUE THREAD

**Issue by alec-horwitz** [learn-co-curriculum/fe-code-along-ex-1#6]
The issues with this lab include but are not limited to the following:
-Git commands in instructions are no longer valid
-Websites where certain required resources reside have changed a bit

The second bullet is an overcome-able obstacle but the first is a bit more complex.

The lab asks you to enter the following command into the terminal: "git co -b main-pages"
This syntax is no longer recognized by git and figuring out a up-to-date equivalent would require far too much research that is outside of the scope of this lab.

**Comment by alec-horwitz** [comment]
CORRECTION: It has come to my attention that the git command is not outdated but instead uses an **unexplained shortcut**. "git co -b main-pages" should be "git checkout -b main-pages". 

This was never explained in the lab and if it hadn't been explained to me by Zac Baston (Thanks Zac!) in the "Ask A Questions" section I may have never figured that out. This omission should be explained/fixed for future students.

**Comment by alec-horwitz** [comment]
UPDATE: Another problem is the download link for which there are already 3 documented "issue"s about the same issue that have been around for 2yrs. There has been nothing done about this issue with the link. It links you to the artist's portfolio site and not to a download of the correct image like it's supposed to. This makes me wonder if all my contributions to this community have been in vain.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback. I'll add a note about this in the readme.
Videos are not particularly easy to maintain, and the majority of the curriculum is being rewritten.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
