### ISSUE TITLE
QUALITY CONTROL NEGLIGENCE

### ISSUE THREAD

**Issue by alec-horwitz** [learn-co-curriculum/fe-code-along-ex-1#8]
There is a problem with the download link for which there are already 3 documented "issue"s. **This same issue that has been around for 2yrs. There has been nothing done about this issue** with the link. It links you to the artist's portfolio site and not to a download of the correct image like it's supposed to.

Each time this was reported, if there was a response, a Charles Pletcher would reply saying:

> Thanks for opening this issue!
> 
> Keep in mind that this space is for specific issues related to the content of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)
> 
> Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

Obviously this problem has nothing to do with the Learn IDE. Especially since the lesson doesn't actually use the IDE (is that yet another problem with this lab that needs fixing?). Nor is this a problem with the Ask a Question form, opening a file, or the lights not working on Learn. This is a problem with the lesson itself. The author of this lesson made a mistake when creating it. If this Charles Pletcher actually looked into/read these issues he would know that.

In one case(from 2yrs ago) someone responds to the "Charles Pletcher response" inquiring about why the issue was never fixed and to this day has not gotten a response. In another case(also from 2yrs ago) the issue got the "Charles Pletcher response" and then was marked closed even though this problem is still present to this day.

I have a strong feeling no one actually reads these. This makes me wonder if all my contributions to this community have been in vain.

**Comment by alec-horwitz** [comment]
If anyone actually does end up reading this I also posted Issue #6 for this lab which details other issues with this lab that might make it impossible for some students to solve on their own.

AGAIN these are problems with the lesson itself not the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn. In fact no issues posted to this day have ever been about anything other then the lesson itself.

**Issue #6 should not be marked as CLOSED until the entire lab is re-done.**

**Comment by drakeltheryuujin** [comment]
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
