### ISSUE TITLE
Links are leading to the wrong place. 

### ISSUE THREAD

**Issue by Cparusso** [learn-co-curriculum/fe-code-along-ex-1#9]
Hi,

The first link here led me to a site with the wrong picture (not a big deal), and the gitignore link no longer leads directly to the gitignore code that should be pasted in to ruby. Both are fairly minor issues but I wanted to bring it to someones attention.

Charlie

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
